version: '2'
services:

  spark-master:
    build: spark-base
    command: /start.sh master
    ports:
      - 8080:8080
      - 4040:4040
      - 7077:7077
    expose:
      - 7077

  spark-slave:
    build: spark-base
    command: /start.sh slave
    ports:
      - 8081
    links:
      - spark-master:spark-master

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock