version: '2'
services:

  spark-master:
    build: spark-base
    command: /start.sh master
    ports:
      - 8080:8080
      - 4040:4040
      - 7077:7077
    expose:
      - 7077

  spark-slave:
    build: spark-base
    command: /start.sh slave
    ports:
      - 8081
    links:
      - spark-master:spark-master

  kafka1:
    image: wurstmeister/kafka
    depends_on:
      - zoo1
#      - zoo2
#      - zoo3
    ports:
      - "9092:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: test-topic-1:1:2,test-topic-2:1:2,test-topic-3:1:2
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181
#      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181,zoo3:2181

#  kafka2:
#    image: wurstmeister/kafka
#    depends_on:
#      - zoo1
#      - zoo2
#      - zoo3
#    ports:
#      - "9093:9092"
#    environment:
#      KAFKA_LOG_DIRS: /kafka
#      KAFKA_BROKER_ID: 2
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
#      KAFKA_ADVERTISED_PORT: 9093
#      KAFKA_LOG_RETENTION_HOURS: "168"
#      KAFKA_LOG_RETENTION_BYTES: "100000000"
#      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181,zoo3:2181
#
#  kafka3:
#    image: wurstmeister/kafka
#    depends_on:
#      - zoo1
#      - zoo2
#      - zoo3
#    ports:
#      - "9094:9092"
#    environment:
#      KAFKA_LOG_DIRS: /kafka
#      KAFKA_BROKER_ID: 3
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
#      KAFKA_ADVERTISED_PORT: 9094
#      KAFKA_LOG_RETENTION_HOURS: "168"
#      KAFKA_LOG_RETENTION_BYTES: "100000000"
#      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181,zoo3:2181

  zoo1:
    image: elevy/zookeeper:latest
    environment:
      MYID: 1
      SERVERS: zoo1
    ports:
      - "2181:2181"
      - "2888"
      - "3888"

#  zoo2:
#    image: elevy/zookeeper:latest
#    environment:
#      MYID: 2
#      SERVERS: zoo1,zoo2,zoo3
#    ports:
#      - "2182:2181"
#      - "2888"
#      - "3888"
#
#  zoo3:
#    image: elevy/zookeeper:latest
#    environment:
#      MYID: 3
#      SERVERS: zoo1,zoo2,zoo3
#    ports:
#      - "2183:2181"
#      - "2888"
#      - "3888"
